import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

const dict = {
  uz: {
    appName: "IshKun",
    tagline: "Kunlik ish — bir tugmada",
    // common
    worker: "Ishchi",
    employer: "Ish beruvchi",
    admin: "Admin",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    back: "Orqaga",
    loading: "Yuklanmoqda…",
    search: "Qidirish",
    city: "Shahar",
    allCities: "Barcha shaharlar",
    date: "Sana",
    status: "Holati",
    logout: "Chiqish",
    profile: "Profil",
    notifications: "Bildirishnomalar",
    language: "Til",
    markAllRead: "Hammasini o'qilgan deb belgilash",
    noData: "Hozircha hech narsa yo'q",
    confirm: "Tasdiqlash",
    required: "Majburiy maydon",
    today: "Bugun",
    // nav
    nav: { browse: "Ishlar", applications: "Arizalarim", shifts: "Shiftlarim", newShift: "Yangi shift", dashboard: "Boshqaruv", admin: "Admin panel", company: "Kompaniya", verification: "Verifikatsiya" },
    // onboarding
    onb: { title: "Rolingizni tanlang", subtitle: "IshKun'ga xush kelibsiz — davom etish uchun rolni tanlang", employerDesc: "Kompaniya yarating va ishchilar uchun shift e'lon qiling", workerDesc: "Mavjud shiftlarga ariza bering va kunlik ish toping", asEmployer: "Ish beruvchi sifatida", asWorker: "Ishchi sifatida", chooseCity: "Shahringizni tanlang", cityHint: "Bu sizga mos shiftlarni filtrlash uchun ishlatiladi" },
    // employer dashboard
    emp: { welcome: "Xush kelibsiz", activeShifts: "Faol shiftlar", totalApps: "Jami arizalar", approved: "Tasdiqlangan", createFirst: "Birinchi shiftingizni e'lon qiling", createFirstHint: "Ishchilarni topish uchun yangi ish e'loni yarating", companyNeeded: "Avval kompaniya profilini yarating", companyNeededHint: "Shift e'lon qilish uchun kompaniya profili kerak", createCompany: "Kompaniya yaratish", recentShifts: "So'nggi shiftlar", noShifts: "Sizda hali shiftlar yo'q" },
    // company
    co: { title: "Kompaniya profili", editTitle: "Kompaniyani tahrirlash", createTitle: "Kompaniya yarating", name: "Kompaniya nomi", industry: "Soha", address: "Manzil", description: "Tavsif", logo: "Logotip URL", saved: "Kompaniya saqlandi", entityType: "Tashkilot turi", legalEntity: "Yuridik shaxs", legalEntityDesc: "Firma, kompaniya yoki tashkilot sifatida ro'yxatdan o'tasiz", individualEntity: "Jismoniy shaxs", individualEntityDesc: "Alohida shaxs sifatida, rasmiy ro'yxatdan o'tgan biznessiz ish beruvchi bo'lasiz", phoneNumber: "Telefon raqami", stir: "STIR", stirHint: "Yuridik shaxslar uchun STIR raqami va davlat ro'yxatidan o'tganlik guvohnomasi kerak bo'ladi.", certificate: "Davlat ro'yxatidan o'tganlik guvohnomasi", individualHint: "Jismoniy shaxs sifatida qo'shimcha hujjat talab qilinmaydi — shaxsingiz profilingizdagi shaxsiy tasdiqlash (JSHSHIR, pasport) orqali aniqlanadi.", mapLink: "Xarita havolasi", mapPickBtn: "Xaritadan belgilash", mapHint: "Xaritada aniq manzilingizni toping, so'ng sahifa havolasini (URL) nusxalab quyidagi maydonga joylashtiring.", phoneFormatError: "Telefon raqami noto'g'ri formatda. Namuna: +998 90 123 45 67", stirFormatError: "STIR 9 ta raqamdan iborat bo'lishi kerak", mapLinkFormatError: "Xarita havolasi http(s):// bilan boshlanishi kerak" },
    // industries
    ind: { savdo: "Savdo", restoran: "Restoran", logistika: "Logistika", event: "Event" },
    // shifts
    shift: { create: "Yangi shift e'loni", edit: "Shiftni tahrirlash", titleLabel: "Sarlavha", description: "Tavsif", date: "Sana", startTime: "Boshlanish vaqti", endTime: "Tugash vaqti", location: "Joylashuv", payment: "To'lov miqdori (so'm)", hourlyRate: "Soatlik stavka (so'm)", hourlyRateHint: "To'lov summasi vaqt bo'yicha avtomatik hisoblanadi", dailyRate: "Kunlik stavka (so'm)", dailyRateHint: "Bu — smena uchun asosiy kunlik to'lov. Agar ishchi rejalashtirilgan vaqtdan ko'proq ishlasa, qo'shimcha soatlar avtomatik hisoblab qo'shiladi (check-in/check-out orqali).", skill: "Lavozim turi", skillAny: "Ahamiyatsiz", workers: "Kerakli ishchilar soni", duration: "Davomiyligi", durationShort: "soat", hourShort: "soat", totalAmount: "Umumiy summa", submit: "E'lon qilish", update: "Yangilash", created: "Shift e'lon qilindi", updated: "Shift yangilandi", open: "Ochiq", filled: "To'lgan", completed: "Yakunlangan", pending_mod: "Moderatsiyada", blocked: "Bloklangan", applicants: "ariza", viewDetails: "Tafsilotlar", markCompleted: "Yakunlandi deb belgilash", mapLink: "Yandex xarita havolasi", mapLinkHint: "Yandex Maps'dan joylashuv havolasini nusxalang va shu yerga joylang", urgentReplacement: "Zudlik bilan kerak!", cancelled: "Bekor qilingan", cancelShift: "Shiftni bekor qilish", cancelConfirmTitle: "Shiftni bekor qilish", cancelConfirmDesc: "Bu smena to'liq bekor qilinadi. Barcha tasdiqlangan va kutilayotgan ishchilarga xabar yuboriladi. Bu amal qaytarib bo'lmaydi.", cancelConfirmBtn: "Bekor qilish", cancelledToast: "Shift bekor qilindi", duplicate: "Nusxalash", duplicatedHint: "Oldingi e'londan nusxalandi. Yangi sana tanlang.", backToList: "Ro'yxatga qaytish", postAnotherDay: "Yana bir kunga joylashtirish", postedSuccessDesc: "Shift ro'yxatga qo'shildi. Yana bir kunga joylashtirishingiz yoki ro'yxatga qaytishingiz mumkin.", mapPickBtn: "Xaritadan belgilash", mapHint: "Xaritada aniq manzilingizni toping, so'ng sahifa havolasini (URL) nusxalab quyidagi maydonga joylashtiring.", mapLinkFormatError: "Xarita havolasi http(s):// bilan boshlanishi kerak" },
    skill: { warehouse: "Ombor xodimi", waiter: "Ofitsiant", cashier: "Kassir", courier: "Kuryer", promoter: "Promouter", event_staff: "Event xodimi", cleaner: "Tozalovchi" },
    sdetail: { address: "Manzil", payTime: "Narx va vaqt", description: "Tavsif", tasksHeading: "Vazifalaringiz", important: "Muhim eslatmalar", requirements: "Talablar", dressCode: "Kiyinish tartibi", viewMap: "Xaritada ko'rish", tasksLabel: "Vazifalar", importantLabel: "Muhim eslatmalar", requirementsLabel: "Talablar", dressCodeLabel: "Kiyinish tartibi" },
    wstat: { apply: "Ariza berish", applied: "Ariza berilgan", booked: "Qabul qilingan", completed: "Bajarilgan", rejected: "Rad etilgan", cancelled: "Bekor qilingan", noShow: "Kelmadi", inProgress: "Ishlanmoqda" },
    rating: { rateCompany: "Kompaniyani baholang", rateWorker: "Ishchini baholang", submit: "Yuborish", commentPh: "Izoh qoldiring (ixtiyoriy)", alreadyRated: "Siz baholadingiz", notRated: "Hali baholanmagan", completedShifts: "tugallangan ish" },
    att: { checkInTitle: "Ishga keldingizmi?", checkInBtn: "Ha, keldim", checkOutTitle: "Ish tugadimi?", checkOutBtn: "Ha, tugadi", waitingConfirm: "Kompaniya ishtirokingizni tasdiqlashini kuting", came: "Keldi", notCame: "Kelmadi", notArrived: "Kelmagan", late: "Kechikmoqda", working: "Ishda", done: "Tugatdi", mismatch: "Nomuvofiqlik", attendance: "Davomat", likedCompany: "Sizga yoqqan kompaniya", goodWorker: "Yaxshi ishchi", confirmReminder: "Iltimos, {name} smenaga kelgani/kelmaganini belgilang", absentTitle: "Ishchi kelmadi", absentDesc: "Ishchi {name} smenaga kelmaganini tasdiqlang.", absentReasonLabel: "Sabab (ixtiyoriy)", absentReasonPh: "Nima uchun kelmadi...", cancellationReason: "Sabab", finalPayment: "Yakuniy to'lov", overtimePrefix: "shundan", overtimeSuffix: "soat qo'shimcha ish uchun" },
    cancelDialog: { title: "Bekor qilish", lateTitle: "Diqqat — qoida buzarlik", lateWarning: "Smenaga 24 soatdan kam qoldi (yoki smena allaqachon boshlangan). Bunday bekor qilish jiddiy qoida buzarlik hisoblanadi va hisobingizga yoziladi. 3 marta qoida buzsangiz, hisobingiz avtomatik bloklanadi.", reasonLabel: "Sababni tanlang", confirmDesc: "Rostdan ham bekor qilasizmi?", confirmBtn: "Bekor qilish", cannotCome: "Kela olmayman", cannotComePast: "Kelolmadim", blockedMsg: "Hisobingiz qoida buzarliklar tufayli bloklangan. Qo'llab-quvvatlash bilan bog'laning.", upcomingReminder: "Eslatma: {title} ishingiz {hours} soatdan keyin boshlanadi", reason: { sick: "Kasal bo'ldim", transport: "Transport muammosi", emergency: "Favqulodda holat", other: "Boshqa sabab", otherPh: "Sababingizni yozing..." } },
    filter: { title: "Filtrlar", date: "Sana", today: "Bugun", tomorrow: "Ertaga", customRange: "Oraliq", dateFrom: "Boshlanish", dateTo: "Tugash", skill: "Lavozim turi", company: "Kompaniya", reset: "Tozalash", showResults: "{n} ta natijani ko'rsatish" },
    // applications
    app: { title: "Arizalar", pending: "Kutilmoqda", approved: "Tasdiqlangan", rejected: "Rad etilgan", completed: "Bajarilgan", approve: "Tasdiqlash", reject: "Rad etish", noApps: "Arizalar yo'q", applicant: "Arizachi", appliedOn: "Ariza sanasi", statusPending: "Kutilmoqda", statusApproved: "Tasdiqlangan", statusRejected: "Rad etilgan", statusCompleted: "Bajarilgan", statusNoShow: "Kelmadi", noShow: "Kelmadi", markDone: "Ish tugadi", markNoShow: "Ishchi kelmadi", approvedMsg: "Ariza tasdiqlandi", rejectedMsg: "Ariza rad etildi", positionFull: "Lavozim to'lgan" },
    // worker
    wrk: { browseTitle: "Mavjud ishlar", searchPlaceholder: "Ish qidirish…", filterCity: "Shahar bo'yicha", filterDate: "Sana bo'yicha", apply: "Ariza berish", applied: "Ariza yuborildi", already: "Siz allaqachon ariza bergansiz", payment: "To'lov", noShifts: "Bu filtrlarga mos shiftlar topilmadi", details: "Shift tafsilotlari", company: "Kompaniya", backToShifts: "Ishlarga qaytish", requirements: "Talab", perWorker: "ishchi kerak", applyNow: "Hoziroq ariza berish", myAppsTitle: "Arizalarim", trackTitle: "Ariza holatini kuzatish", noMyApps: "Siz hech qanday ariza bermagansiz", viewShift: "Shiftni ko'rish", cancelApp: "Arizani bekor qilish", confirmCancel: "Haqiqatan ham bekor qilmoqchimisiz?", confirmCancelDesc: "Arizangiz bekor qilinadi.", completedJobs: "Tugallangan ishlar", noCompleted: "Tugallangan ishlar yo'q", sectionPending: "Kutilmoqda tasdiqlanishni", sectionApproved: "Qabul qilingansiz", sectionCompleted: "Ishlangan", sectionEmpty: "Bo'sh", tabPending: "Kutilmoqda", tabApproved: "Tasdiqlandi", tabCompleted: "Bajarildi", tabNoShow: "Kelmadi", sameDayConflict: "Sizda bu kunga boshqa ariza bor — kuniga faqat bitta ish olish mumkin" },
    // profile
    prf: { title: "Profil", fullName: "Ism familiya", phone: "Telefon raqami", role: "Rol", city: "Shahar", image: "Profil rasmi", saved: "Profil saqlandi", phoneFormatError: "Telefon raqami noto'g'ri formatda. Namuna: +998 90 123 45 67", memberSince: "A'zo bo'lgan sana", changeRole: "Rolni o'zgartirish", changeRoleHint: "Bu saf uchun rol o'zgartirilsa, e'lonlaringiz va arizalaringiz saqlanadi", deleteAccount: "Hisobni o'chirish", deleteAccountConfirm: "Hisobni o'chirishni tasdiqlang", deleteAccountDesc: "Bu amal qaytarib bo'lmaydi. Barcha ma'lumotlaringiz butunlay o'chiriladi.", deleteAccountConfirmBtn: "O'chirish", deleting: "O'chirilmoqda…" },
    // notifications
    notif: { title: "Bildirishnomalar", empty: "Bildirishnomalar yo'q", approved: "Arizangiz tasdiqlandi", rejected: "Arizangiz rad etildi", newApp: "Yangi ariza", shiftDone: "Shift yakunlandi", noShow: "Ishchi kelmadi", justNow: "hozir" },
    kyc: { title: "Verifikatsiya", tab: "Verifikatsiya", personalInfo: "Shaxsiy ma'lumotlar", documents: "Hujjatlar", financial: "Moliyaviy ma'lumotlar", phone: "Telefon raqami", phoneHint: "Admin siz bilan bog'lanish uchun", phoneFormatError: "Telefon raqami noto'g'ri formatda. Namuna: +998 90 123 45 67", jshshir: "JSHSHIR", jshshirHint: "14 raqamli shaxs identifikatsiya raqami", jshshirError: "JSHSHIR 14 ta raqamdan iborat bo'lishi kerak", dob: "Tug'ilgan sana", address: "Joriy manzil", addressPh: "Viloyat, shahar, ko'cha, uy",     passportFront: "Pasport/ID oldi", passportBack: "Pasport/ID orqa", passportHint: "Bu biz sizni rasmiy ishga joylashtirishimiz uchun kerak", liveness: "Liveness tekshiruvi (ID bilan selfi)", livenessHint: "ID kartangizni ushlab turgan holda selfi rasm", studentId: "Talabalar ID kartasi", bankCard: "Uzcard/Humo karta raqami", bankCardHint: "O'z ismingizga bog'langan karta", selfEmployed: "O'z-o'zini band qilgan (self-employed)", selfEmployedCert: "Self-employed guvohnomasi", pending: "Verifikatsiya kutilmoqda", submitted: "Hujjatlar yuborildi — tekshirilmoqda", verified: "Verifikatsiya tasdiqlandi", rejected: "Verifikatsiya rad etildi", verifiedMsg: "Profilingiz to'liq tasdiqlangan. Barcha ishlarga ariza berishingiz mumkin.", mustVerify: "Ishga ariza berish uchun profilingizni verifikatsiyadan o'tkazing", verifyNow: "Verifikatsiyadan o'tish", submit: "Hujjatlarni yuborish", submitError: "Yuborish amalga oshmadi", requiredError: "Barcha majburiy maydonlarni to'ldiring", docsError: "Barcha hujjatlarni yuklang", cardError: "Karta raqamini to'g'ri kiriting", ageError: "Ro'yxatdan o'tish uchun kamida 18 yoshda bo'lishingiz kerak.", yes: "Ha", no: "Yo'q", noPending: "Verifikatsiya kutilayotgan foydalanuvchilar yo'q", review: "Ko'rib chiqish", approve: "Tasdiqlash", reject: "Rad etish", rejectNotePh: "Rad etish sababi (masalan: xira rasm)" },
    // admin
    adm: { title: "Admin panel", overview: "Umumiy ko'rinish", allShifts: "Barcha shiftlar", allUsers: "Foydalanuvchilar", totalUsers: "Foydalanuvchilar", totalShifts: "Shiftlar", totalCompanies: "Kompaniyalar", totalApps: "Arizalar", moderate: "Moderatsiya", block: "Blok", unblock: "Blokdan chiqarish", approve_mod: "Tasdiqla", blocked: "Bloklangan", approved: "Tasdiqlangan", pending: "Moderatsiyada", viewShift: "Ko'rish", noShifts: "Shiftlar yo'q", users: "Foydalanuvchilar", shifts: "Shiftlar", role: "Rol", created: "Yaratilgan", open: "Ochiq", filled: "To'lgan", completed: "Yakunlangan", notifications: "Bildirishnomalar", noShowNotif: "Ishchi kelmadi xabarlari", noNotifs: "Bildirishnomalar yo'q", inviteTab: "Taklif qilish", inviteTitle: "Foydalanuvchini taklif qilish", inviteHint: "Email orqali yangi foydalanuvchini ilovaga taklif qiling", inviteEmail: "Email manzili", inviteEmailReq: "Email manzilini kiriting", inviteRole: "Rol", inviteRoleUser: "Foydalanuvchi", inviteRoleUserHint: "Ishchi yoki ish beruvchi sifatida ro'yxatdan o'tadi", inviteRoleAdmin: "Admin", inviteRoleAdminHint: "To'liq boshqaruv huquqi", inviteSend: "Taklif yuborish", inviteSending: "Yuborilmoqda…", inviteSent: "Taklif yuborildi:", inviteError: "Taklif yuborish amalga oshmadi", attendanceIssues: "Davomat muammolari", unresolved: "Hal qilinmagan", noAttendanceIssues: "Davomat muammolari yo'q", statusActive: "Faol", statusPaused: "To'xtatilgan", statusBlocked: "Bloklangan", confirmBlock: "Blokla", reactivate: "Qayta faollashtirish" }
  },
  ru: {
    appName: "IshKun",
    tagline: "Подённая работа — одной кнопкой",
    worker: "Работник",
    employer: "Работодатель",
    admin: "Админ",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    back: "Назад",
    loading: "Загрузка…",
    search: "Поиск",
    city: "Город",
    allCities: "Все города",
    date: "Дата",
    status: "Статус",
    logout: "Выйти",
    profile: "Профиль",
    notifications: "Уведомления",
    language: "Язык",
    markAllRead: "Отметить все прочитанными",
    noData: "Пока ничего нет",
    confirm: "Подтвердить",
    required: "Обязательное поле",
    today: "Сегодня",
    nav: { browse: "Работы", applications: "Мои заявки", shifts: "Мои смены", newShift: "Новая смена", dashboard: "Управление", admin: "Админ-панель", company: "Компания", verification: "Верификация" },
    onb: { title: "Выберите роль", subtitle: "Добро пожаловать в IshKun — выберите роль, чтобы продолжить", employerDesc: "Создайте компанию и публикуйте смены для работников", workerDesc: "Подавайте заявки на смены и находите подённую работу", asEmployer: "Как работодатель", asWorker: "Как работник", chooseCity: "Выберите город", cityHint: "Используется для фильтрации подходящих смен" },
    emp: { welcome: "Добро пожаловать", activeShifts: "Активные смены", totalApps: "Всего заявок", approved: "Подтверждено", createFirst: "Опубликуйте первую смену", createFirstHint: "Создайте объявление о работе, чтобы найти работников", companyNeeded: "Сначала создайте профиль компании", companyNeededHint: "Для публикации смен нужен профиль компании", createCompany: "Создать компанию", recentShifts: "Недавние смены", noShifts: "У вас пока нет смен" },
    co: { title: "Профиль компании", editTitle: "Редактировать компанию", createTitle: "Создать компанию", name: "Название компании", industry: "Сфера", address: "Адрес", description: "Описание", logo: "URL логотипа", saved: "Компания сохранена", entityType: "Тип организации", legalEntity: "Юридическое лицо", legalEntityDesc: "Регистрируетесь как фирма, компания или организация", individualEntity: "Физическое лицо", individualEntityDesc: "Выступаете как частное лицо, работодатель без официальной регистрации бизнеса", phoneNumber: "Номер телефона", stir: "STIR", stirHint: "Для юридических лиц требуется номер STIR и свидетельство о государственной регистрации.", certificate: "Свидетельство о государственной регистрации", individualHint: "Как физлицо доп. документы не требуются — ваша личность подтверждается через верификацию профиля (ПИНФЛ, паспорт).", mapLink: "Ссылка на карту", mapPickBtn: "Выбрать на карте", mapHint: "Найдите точный адрес на карте, затем скопируйте ссылку страницы (URL) и вставьте в поле ниже.", phoneFormatError: "Неверный формат номера телефона. Пример: +998 90 123 45 67", stirFormatError: "STIR должен состоять из 9 цифр", mapLinkFormatError: "Ссылка карты должна начинаться с http(s)://" },
    ind: { savdo: "Торговля", restoran: "Ресторан", logistika: "Логистика", event: "Ивент" },
    shift: { create: "Новая смена", edit: "Редактировать смену", titleLabel: "Заголовок", description: "Описание", date: "Дата", startTime: "Время начала", endTime: "Время окончания", location: "Место", payment: "Оплата (сум)", hourlyRate: "Ставка в час (сум)", hourlyRateHint: "Сумма оплаты рассчитывается автоматически по времени", dailyRate: "Дневная ставка (сум)", dailyRateHint: "Это — основная дневная оплата за смену. Если работник отработает больше запланированного времени, дополнительные часы будут рассчитаны и добавлены автоматически (через check-in/check-out).", skill: "Должность", skillAny: "Неважно", workers: "Нужно работников", duration: "Длительность", durationShort: "ч", hourShort: "ч", totalAmount: "Итоговая сумма", submit: "Опубликовать", update: "Обновить", created: "Смена опубликована", updated: "Смена обновлена", open: "Открыта", filled: "Заполнена", completed: "Завершена", pending_mod: "На модерации", blocked: "Заблокирована", applicants: "заявок", viewDetails: "Подробности", markCompleted: "Отметить завершённой", mapLink: "Ссылка Яндекс Карт", mapLinkHint: "Скопируйте ссылку места из Яндекс Карт и вставьте сюда", urgentReplacement: "Срочно нужен!", cancelled: "Отменена", cancelShift: "Отменить смену", cancelConfirmTitle: "Отменить смену", cancelConfirmDesc: "Эта смена будет полностью отменена. Все подтверждённые и ожидающие работники получат уведомление. Это действие необратимо.", cancelConfirmBtn: "Отменить", cancelledToast: "Смена отменена", duplicate: "Дублировать", duplicatedHint: "Скопировано из предыдущего объявления. Выберите новую дату.", backToList: "Вернуться к списку", postAnotherDay: "Разместить ещё на один день", postedSuccessDesc: "Смена добавлена в список. Вы можете разместить ещё на один день или вернуться к списку.", mapPickBtn: "Выбрать на карте", mapHint: "Найдите точный адрес на карте, затем скопируйте ссылку страницы (URL) и вставьте в поле ниже.", mapLinkFormatError: "Ссылка карты должна начинаться с http(s)://" },
    skill: { warehouse: "Кладовщик", waiter: "Официант", cashier: "Кассир", courier: "Курьер", promoter: "Промоутер", event_staff: "Event-персонал", cleaner: "Уборщик" },
    sdetail: { address: "Адрес", payTime: "Оплата и время", description: "Описание", tasksHeading: "Ваши задачи", important: "Важные примечания", requirements: "Требования", dressCode: "Дресс-код", viewMap: "На карте", tasksLabel: "Задачи", importantLabel: "Важные примечания", requirementsLabel: "Требования", dressCodeLabel: "Дресс-код" },
    wstat: { apply: "Подать заявку", applied: "Заявка подана", booked: "Принят", completed: "Выполнено", rejected: "Отклонено", cancelled: "Отменено", noShow: "Не пришёл", inProgress: "Выполняется" },
    rating: { rateCompany: "Оцените компанию", rateWorker: "Оцените работника", submit: "Отправить", commentPh: "Оставьте комментарий (необязательно)", alreadyRated: "Вы оценили", notRated: "Ещё нет оценок", completedShifts: "завершённых работ" },
    att: { checkInTitle: "Вы пришли на работу?", checkInBtn: "Да, пришёл", checkOutTitle: "Работа закончена?", checkOutBtn: "Да, закончена", waitingConfirm: "Ожидайте подтверждения компании", came: "Пришёл", notCame: "Не пришёл", notArrived: "Не пришёл", late: "Опаздывает", working: "На работе", done: "Завершил", mismatch: "Несоответствие", attendance: "Посещаемость", likedCompany: "Понравившаяся компания", goodWorker: "Хороший работник", confirmReminder: "Пожалуйста, отметьте, пришёл ли {name} на смену", absentTitle: "Работник не пришёл", absentDesc: "Подтвердите, что {name} не пришёл на смену.", absentReasonLabel: "Причина (необязательно)", absentReasonPh: "Почему не пришёл...", cancellationReason: "Причина", finalPayment: "Итоговая оплата", overtimePrefix: "из них", overtimeSuffix: "ч за дополнительную работу" },
    cancelDialog: { title: "Отмена", lateTitle: "Внимание — нарушение правил", lateWarning: "До смены осталось меньше 24 часов (или смена уже началась). Такая отмена считается серьёзным нарушением и будет записана на ваш счёт. После 3 нарушений ваш аккаунт будет автоматически заблокирован.", reasonLabel: "Выберите причину", confirmDesc: "Вы действительно хотите отменить?", confirmBtn: "Отменить", cannotCome: "Не смогу прийти", cannotComePast: "Не смог прийти", blockedMsg: "Ваш аккаунт заблокирован за нарушения. Обратитесь в поддержку.", upcomingReminder: "Напоминание: работа {title} начнётся через {hours} ч", reason: { sick: "Заболел", transport: "Транспортная проблема", emergency: "Чрезвычайная ситуация", other: "Другая причина", otherPh: "Опишите причину..." } },
    filter: { title: "Фильтры", date: "Дата", today: "Сегодня", tomorrow: "Завтра", customRange: "Диапазон", dateFrom: "С", dateTo: "По", skill: "Должность", company: "Компания", reset: "Сбросить", showResults: "Показать {n} результатов" },
    app: { title: "Заявки", pending: "Ожидает", approved: "Подтверждена", rejected: "Отклонена", completed: "Выполнена", approve: "Подтвердить", reject: "Отклонить", noApps: "Заявок нет", applicant: "Заявитель", appliedOn: "Дата заявки", statusPending: "Ожидает", statusApproved: "Подтверждена", statusRejected: "Отклонена", statusCompleted: "Выполнена", statusNoShow: "Не пришёл", noShow: "Не пришёл", markDone: "Работа завершена", markNoShow: "Работник не пришёл", approvedMsg: "Заявка подтверждена", rejectedMsg: "Заявка отклонена", positionFull: "Места заполнены" },
    wrk: { browseTitle: "Доступные работы", searchPlaceholder: "Поиск работы…", filterCity: "По городу", filterDate: "По дате", apply: "Подать заявку", applied: "Заявка отправлена", already: "Вы уже подали заявку", payment: "Оплата", noShifts: "Смены по фильтрам не найдены", details: "Подробности смены", company: "Компания", backToShifts: "К списку работ", requirements: "Требования", perWorker: "нужно работников", applyNow: "Подать заявку сейчас", myAppsTitle: "Мои заявки", trackTitle: "Отслеживание статуса", noMyApps: "Вы ещё не подавали заявок", viewShift: "Открыть смену", cancelApp: "Отменить заявку", confirmCancel: "Вы действительно хотите отменить?", confirmCancelDesc: "Ваша заявка будет отменена.", completedJobs: "Завершённые работы", noCompleted: "Нет завершённых работ", sectionPending: "Ожидает подтверждения", sectionApproved: "Вы приняты", sectionCompleted: "Выполнено", sectionEmpty: "Пусто", tabPending: "Ожидает", tabApproved: "Подтверждено", tabCompleted: "Выполнено", tabNoShow: "Не пришёл", sameDayConflict: "У вас уже есть заявка на этот день — можно брать только одну работу в день" },
    prf: { title: "Профиль", fullName: "Имя и фамилия", phone: "Телефон", role: "Роль", city: "Город", image: "Фото профиля", saved: "Профиль сохранён", phoneFormatError: "Неверный формат номера телефона. Пример: +998 90 123 45 67", memberSince: "Дата регистрации", changeRole: "Сменить роль", changeRoleHint: "При смене роли ваши объявления и заявки сохранятся", deleteAccount: "Удалить аккаунт", deleteAccountConfirm: "Подтвердите удаление аккаунта", deleteAccountDesc: "Это действие необратимо. Все ваши данные будут безвозвратно удалены.", deleteAccountConfirmBtn: "Удалить", deleting: "Удаление…" },
    notif: { title: "Уведомления", empty: "Уведомлений нет", approved: "Ваша заявка подтверждена", rejected: "Ваша заявка отклонена", newApp: "Новая заявка", shiftDone: "Смена завершена", noShow: "Работник не пришёл", justNow: "сейчас" },
    kyc: { title: "Верификация", tab: "Верификация", personalInfo: "Личные данные", documents: "Документы", financial: "Финансовые данные", phone: "Номер телефона", phoneHint: "Для связи с вами от администрации", phoneFormatError: "Неверный формат номера телефона. Пример: +998 90 123 45 67", jshshir: "ПИНФЛ", jshshirHint: "14-значный идентификационный номер", jshshirError: "ПИНФЛ должен содержать 14 цифр", dob: "Дата рождения", address: "Текущий адрес", addressPh: "Область, город, улица, дом",     passportFront: "Паспорт/ID лицевая", passportBack: "Паспорт/ID обратная", passportHint: "Это необходимо, чтобы мы могли устроить вас на официальную работу", liveness: "Liveness-проверка (селфи с ID)", livenessHint: "Селфи с удостоверением в руках", studentId: "Студенческий ID", bankCard: "Номер карты Uzcard/Humo", bankCardHint: "Карта на ваше имя", selfEmployed: "Самозанятый", selfEmployedCert: "Свидетельство самозанятого", pending: "Ожидает верификации", submitted: "Документы отправлены — на проверке", verified: "Верификация подтверждена", rejected: "Верификация отклонена", verifiedMsg: "Ваш профиль полностью подтверждён. Вы можете подавать заявки на все работы.", mustVerify: "Для подачи заявки пройдите верификацию профиля", verifyNow: "Пройти верификацию", submit: "Отправить документы", submitError: "Не удалось отправить", requiredError: "Заполните все обязательные поля", docsError: "Загрузите все документы", cardError: "Введите корректный номер карты", ageError: "Для регистрации вам должно быть не менее 18 лет.", yes: "Да", no: "Нет", noPending: "Нет пользователей на верификации", review: "Проверить", approve: "Одобрить", reject: "Отклонить", rejectNotePh: "Причина отказа (например: размытое фото)" },
    adm: { title: "Админ-панель", overview: "Обзор", allShifts: "Все смены", allUsers: "Пользователи", totalUsers: "Пользователи", totalShifts: "Смены", totalCompanies: "Компании", totalApps: "Заявки", moderate: "Модерация", block: "Блок", unblock: "Разблокировать", approve_mod: "Одобрить", blocked: "Заблокирована", approved: "Одобрена", pending: "На модерации", viewShift: "Открыть", noShifts: "Смен нет", users: "Пользователи", shifts: "Смены", role: "Роль", created: "Создан", open: "Открыта", filled: "Заполнена", completed: "Завершена", notifications: "Уведомления", noShowNotif: "Сообщения о неявке", noNotifs: "Уведомлений нет", inviteTab: "Пригласить", inviteTitle: "Пригласить пользователя", inviteHint: "Пригласите нового пользователя в приложение по email", inviteEmail: "Email адрес", inviteEmailReq: "Введите email адрес", inviteRole: "Роль", inviteRoleUser: "Пользователь", inviteRoleUserHint: "Зарегистрируется как работник или работодатель", inviteRoleAdmin: "Админ", inviteRoleAdminHint: "Полный доступ к управлению", inviteSend: "Отправить приглашение", inviteSending: "Отправка…", inviteSent: "Приглашение отправлено:", inviteError: "Не удалось отправить приглашение", attendanceIssues: "Проблемы с посещаемостью", unresolved: "Не разрешено", noAttendanceIssues: "Нет проблем с посещаемостью", statusActive: "Активен", statusPaused: "Приостановлен", statusBlocked: "Заблокирован", confirmBlock: "Заблокировать", reactivate: "Реактивировать" }
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('ishkun_lang') || 'uz');

  useEffect(() => {
    localStorage.setItem('ishkun_lang', lang);
  }, [lang]);

  const t = useCallback((path) => {
    const parts = path.split('.');
    let val = dict[lang];
    for (const p of parts) {
      if (val == null) return path;
      val = val[p];
    }
    return val == null ? path : val;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}